### ISSUE TITLE
Editing Views

### ISSUE THREAD

**Issue by macgill4444** [jipiboily/monologue#240]
This might seem like a stupid question but how can I generate the views/edit the views for monologue. I have installed the gem and it works well but I want to be able to edit the posts. Anyway to do this? Thanks for making a great gem!

**Comment by jasonbuehler** [comment]
ditto for this, anyone have any idea how to do this?

**Comment by msevestre** [comment]
It's fairly easy actually once you know how :)
Simply create a file in your app at the exact same path. It will be loaded instead of the one defined in Monologue

For example:
You want to override the partial `_post.html.erb` with your own

Simply create a file called `_post.html.erb` at the same location

`app/views/monologue/posts/_post.html.erb`

Using this technique, I was able to completely customize header etc of posts

Let me know if that helps, 

Cheers

@macgill4444 Sorry for the late reply, I did not see the email before

**Comment by jasonbuehler** [comment]
Great, thanks @msevestre !

**Comment by macgill4444** [comment]
Thanks so much @msevestre

**Comment by msevestre** [comment]
Excellent. Glad I could help. Cheers
