### ISSUE TITLE
Preview of blog post on index page - adjustable? 

### ISSUE THREAD

**Issue by lukasrplus** [jipiboily/monologue#268]
Hi there,

I just wonder if there's any way adjust the amount of characters that is displayed as preview in the posts/index.

Furthermore - is it generally impossible to change the index and show views of posts?

Any ideas or answers are highly appreciated!

Thank you!

Lukas

**Comment by msevestre** [comment]
Hi @lukasrplus 
There is no config for that unfortunately. The magic number is 1000 and can be found
https://github.com/jipiboily/monologue/blob/master/app/views/monologue/posts/_post.html.erb#L5

That would be awesome to define a parameter in the configuration. If you have time, a PR would be much appreciated :)

Regarding overriding of index view and any other views. You can definitely change ANY view the way you want it to appear. Because Monologue is mounted as  a rails engine, the view defined in your apps under the same path will be the one used. 

So let say you want to override the `index.html.erb` page (original is here https://github.com/jipiboily/monologue/blob/master/app/views/monologue/posts/index.html.erb), you can simply create a view under your app view folder at the exact same location (e.g. `app/views/monologue/posts/index.html.erb`) and put what ever you want in it. The same goes of course for all partials as well

Makes sense?

Cheers

**Comment by lukasrplus** [comment]
Hi @msevestre !

Thank you for your answer!!!

Honestly, I am not sure how to create a config change for the "1000" (sorry I have never built or contributed to a gem before and would need further instruction for helping out on that).

But, I did find a way to work around it manually:

In order to make everything work, I did realize that my application.html.erb files have to be located in (I am using /blog):
app/views/blog/layouts/monologue/...

Whereas anything related to the posts has to be put in the folder you mentioned:
app/views/monologue/posts/_post.html.erb

By simply moving the index.html.erb and the partials it this folder I could customize them - also changing the value for the preview to 500.

Do you see any hickups with this?

Thank you once again and all the best from Vienna,

Lukas

**Comment by msevestre** [comment]
ok I have added a parameter preview_size. DEfault is 1000 but it can be set to anything in the initilizer. Thanks for the idea
